spring.application.name=erp

# PostgreSQL datasource (local development)
spring.datasource.url=jdbc:postgresql://localhost:5432/erp
spring.datasource.username=${POSTGRES_USERNAME:postgres}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
